# ─────────────────────────────────────────────────────────────
# TRAINING DATA FOR GRIEVANCE CLASSIFIER
# 80+ complaints per department = 480+ total samples
# Language is intentionally varied — short, long, formal,
# informal — to make the model robust to real student writing.
# ─────────────────────────────────────────────────────────────

TRAINING_DATA = [

    # ── HOSTEL (80 samples) ──────────────────────────────────
    ("The water supply in my hostel room has been cut for 3 days", "Hostel"),
    ("Mess food quality is very poor and sometimes has insects in it", "Hostel"),
    ("My hostel room door lock is broken and I cannot secure my belongings", "Hostel"),
    ("The warden is not available during emergency hours", "Hostel"),
    ("There is no hot water in the bathroom during winter mornings", "Hostel"),
    ("Cockroaches and rats are found frequently in the hostel kitchen", "Hostel"),
    ("The hostel gate is closed before the permitted entry time", "Hostel"),
    ("My roommate plays loud music late at night and disturbs my sleep", "Hostel"),
    ("The ceiling fan in room 204 is not working since last month", "Hostel"),
    ("Hostel mess is not serving food as per the declared menu", "Hostel"),
    ("The bathroom drainage is completely blocked on the second floor", "Hostel"),
    ("There is no electricity in block B from 10 PM to 6 AM daily", "Hostel"),
    ("The mattress in my room is torn and unhygienic", "Hostel"),
    ("Laundry service in the hostel is not functioning this week", "Hostel"),
    ("The hostel notice board has outdated information about rules", "Hostel"),
    ("Drinking water filter in the hostel corridor is broken", "Hostel"),
    ("My hostel room window glass is cracked and cold air enters at night", "Hostel"),
    ("The geyser in block A bathroom is not heating water properly", "Hostel"),
    ("Hostel mess timings were changed without informing students", "Hostel"),
    ("There are mosquitoes everywhere in the hostel rooms at night", "Hostel"),
    ("The hostel common room TV has been broken for two weeks", "Hostel"),
    ("Cleanliness in hostel washrooms is very poor and smells bad", "Hostel"),
    ("I was denied entry to the hostel because I came back at 10:05 PM", "Hostel"),
    ("The dustbins in the hostel corridor are not emptied for days", "Hostel"),
    ("My hostel room light bulb and tube light are not working", "Hostel"),
    ("The mess is serving the same food every single day this week", "Hostel"),
    ("There is a water leakage from the ceiling in my room during rain", "Hostel"),
    ("The hostel warden behaved rudely when I reported the problem", "Hostel"),
    ("Pest control has not been done in the hostel for several months", "Hostel"),
    ("The hostel study room is always locked and not accessible to students", "Hostel"),
    ("Food served in the hostel mess is often cold and not fresh", "Hostel"),
    ("My room allocation was changed without any prior notice", "Hostel"),
    ("The hostel fire extinguisher on our floor appears to be expired", "Hostel"),
    ("Block C has no water supply from morning until evening", "Hostel"),
    ("The hostel compound wall is damaged and creates a safety risk", "Hostel"),
    ("Hostel electricity goes off every night which affects my studies", "Hostel"),
    ("There is construction noise near the hostel affecting sleep", "Hostel"),
    ("The mess staff is rude and serves insufficient portions of food", "Hostel"),
    ("There is no power backup in my hostel block during outages", "Hostel"),
    ("The bed in my hostel room is broken and I hurt my back", "Hostel"),
    ("Hostel visitors are not being allowed inside even during permitted hours", "Hostel"),
    ("The hostel common area is never cleaned by the housekeeping staff", "Hostel"),
    ("My hostel room has a very bad stench from the drainage below", "Hostel"),
    ("The mess is charging extra money beyond the declared fees", "Hostel"),
    ("I have been assigned a room with a broken window and no repair done", "Hostel"),
    ("The hostel night watchman is often absent from his post", "Hostel"),
    ("Stray dogs are entering the hostel premises at night", "Hostel"),
    ("The hostel mess does not offer any vegetarian options on Sundays", "Hostel"),
    ("My cupboard in the hostel room has no lock and things go missing", "Hostel"),
    ("There is severe water shortage in the hostel every morning", "Hostel"),
    ("The hostel mess serves food that caused stomach issues to many students", "Hostel"),
    ("Unauthorized people are found roaming inside the hostel premises", "Hostel"),
    ("The hostel room heater provided is not working in cold weather", "Hostel"),
    ("I found lizards and insects inside my hostel room regularly", "Hostel"),
    ("The hostel warden is not responding to maintenance complaints", "Hostel"),
    ("There is mold growing on the walls of my hostel room", "Hostel"),
    ("Hostel block D has not had a proper cleaning in over a month", "Hostel"),
    ("The solar water heater for the hostel has stopped working", "Hostel"),
    ("My hostel roommate was changed without any reason given to me", "Hostel"),
    ("The mess food during exams is especially poor and unnutritious", "Hostel"),
    ("Water taps in my hostel floor corridor are dripping and wasting water", "Hostel"),
    ("The doors of bathroom stalls in the hostel do not close properly", "Hostel"),
    ("Night curfew timing is inconsistently enforced by the warden", "Hostel"),
    ("The hostel room has ants everywhere especially near the study table", "Hostel"),
    ("Hostel mess stopped serving dinner before the official closing time", "Hostel"),
    ("The hostel reading room has insufficient lighting for studying", "Hostel"),
    ("My hostel room has a strong smell of sewage from the drainage pipe", "Hostel"),
    ("The hostel main gate CCTV camera has been broken for weeks", "Hostel"),
    ("Excessive noise from construction next to hostel affects concentration", "Hostel"),
    ("The hostel mess has not been cleaned properly after each meal", "Hostel"),
    ("I was fined by the hostel for a reason that was not communicated", "Hostel"),
    ("The hostel does not provide adequate storage space for students", "Hostel"),
    ("Bathroom exhaust fans in hostel block B are all not working", "Hostel"),
    ("The mess vendor changed the menu without approval from students", "Hostel"),
    ("Our hostel floor has been without running water for five days", "Hostel"),
    ("The hostel room allocated to me is much smaller than what was promised", "Hostel"),
    ("Hostel staff is not sanitizing the mess area after COVID protocols", "Hostel"),
    ("There is no warm food option available in the hostel mess at night", "Hostel"),
    ("The warden confiscated my personal items without proper justification", "Hostel"),

    # ── IT (80 samples) ──────────────────────────────────────
    ("The college WiFi is extremely slow and disconnects every few minutes", "IT"),
    ("I cannot log in to the student portal despite entering correct credentials", "IT"),
    ("The computer lab systems are very old and crash frequently", "IT"),
    ("My student email account has been deactivated without any reason", "IT"),
    ("The college website shows an error when I try to access my results", "IT"),
    ("The internet connection in the library is not working since yesterday", "IT"),
    ("I cannot access the online exam portal from the college network", "IT"),
    ("The college ERP system shows wrong data for my attendance", "IT"),
    ("The printer in the computer lab is not working for the past week", "IT"),
    ("My account on the learning management system has been locked", "IT"),
    ("The projector in seminar hall 2 is not displaying output properly", "IT"),
    ("WiFi password was changed but students were not informed", "IT"),
    ("The college network blocks many legitimate educational websites", "IT"),
    ("I am unable to submit my assignment online due to portal errors", "IT"),
    ("The computer lab does not have licensed antivirus software installed", "IT"),
    ("The college server was down during my online examination", "IT"),
    ("My registration number is incorrectly entered in the college database", "IT"),
    ("The college app crashes every time I try to check my timetable", "IT"),
    ("I am not receiving OTP on my registered email for portal login", "IT"),
    ("The college website fee payment gateway is not working", "IT"),
    ("Network cables in lab 3 are exposed and creating a safety hazard", "IT"),
    ("My laptop cannot connect to the campus network even with correct password", "IT"),
    ("The online attendance system shows me absent on days I was present", "IT"),
    ("I cannot download my admit card from the college portal", "IT"),
    ("The college WiFi does not work in the hostel block area", "IT"),
    ("The LMS course materials are not loading for my enrolled subjects", "IT"),
    ("I reported a software issue to IT department but got no response", "IT"),
    ("The college email server is rejecting emails from external addresses", "IT"),
    ("Several computers in lab 1 do not have functional keyboards", "IT"),
    ("The college database has my wrong date of birth", "IT"),
    ("I cannot reset my student portal password using the reset option", "IT"),
    ("The WiFi router on the third floor of the academic block is broken", "IT"),
    ("The college network firewall blocks access to Google Classroom", "IT"),
    ("My online fee payment was deducted twice from my account", "IT"),
    ("The smart board in classroom 301 is not responding to touch", "IT"),
    ("I am unable to register for elective courses on the portal", "IT"),
    ("The college server frequently goes down during peak usage hours", "IT"),
    ("Software required for our course is not installed in the computer lab", "IT"),
    ("I cannot view my internal marks on the college portal", "IT"),
    ("The IT helpdesk does not respond to emails or calls", "IT"),
    ("The college website times out when trying to upload documents", "IT"),
    ("WiFi signal does not reach the ground floor of the hostel", "IT"),
    ("The online library catalog system is not loading for several days", "IT"),
    ("My college ID card is not working for biometric attendance", "IT"),
    ("The college portal shows wrong semester data for my account", "IT"),
    ("USB ports in computer lab are disabled and I cannot save my work", "IT"),
    ("The online examination system kicked me out during the exam", "IT"),
    ("I cannot change my registered mobile number on the student portal", "IT"),
    ("The college network speed is so slow that video lectures cannot load", "IT"),
    ("An error appears when I try to print hall ticket from the website", "IT"),
    ("The college WiFi blocks WhatsApp and other apps needed for study groups", "IT"),
    ("My digital marksheet on the portal has an incorrect subject name", "IT"),
    ("The internet in the reading room stops working after 9 PM", "IT"),
    ("The college mobile app does not show updated fee payment status", "IT"),
    ("My college email inbox is full and I cannot receive new emails", "IT"),
    ("The software license for the design tool in lab 4 has expired", "IT"),
    ("I cannot upload my project report on the portal as the file size limit is too low", "IT"),
    ("The college WiFi disconnects whenever there is a power fluctuation", "IT"),
    ("The online grievance portal itself is not working and shows errors", "IT"),
    ("Lab computers do not have updated browsers for web-based assignments", "IT"),
    ("My student portal account was hacked and I need immediate assistance", "IT"),
    ("The college network does not support video calls needed for remote interviews", "IT"),
    ("I am unable to access previous semester results on the portal", "IT"),
    ("The campus WiFi requires re-login every 30 minutes which is disruptive", "IT"),
    ("The college IT department took my laptop for repair and has not returned it", "IT"),
    ("The biometric attendance machine on second floor is not reading fingerprints", "IT"),
    ("College portal does not work on mobile browsers only on desktop", "IT"),
    ("The computer lab booking system online is not showing available slots", "IT"),
    ("My scholarship application form on the portal cannot be submitted", "IT"),
    ("The college provided email has very limited storage space", "IT"),
    ("I cannot download my bonafide certificate from the student portal", "IT"),
    ("The projector remote in lab 2 is missing and classes are disrupted", "IT"),
    ("College app notifications for exam schedule are not being received", "IT"),
    ("The WiFi speed test shows less than 1 Mbps in the academic building", "IT"),
    ("I submitted a complaint on the IT portal but no ticket number was generated", "IT"),
    ("The college intranet portal is accessible only from specific rooms", "IT"),
    ("System restoration after a virus removed all my saved project files in lab", "IT"),

    # ── ACADEMIC (80 samples) ────────────────────────────────
    ("My attendance is showing 60% but I have attended all classes this month", "Academic"),
    ("The professor has not conducted a single class in the past two weeks", "Academic"),
    ("My internal marks were entered incorrectly in the system", "Academic"),
    ("The exam timetable clashes with two of my subjects on the same day and time", "Academic"),
    ("I was marked absent in a class I clearly attended and have proof", "Academic"),
    ("The faculty member is not completing the syllabus before exams", "Academic"),
    ("My result shows I failed in a subject but I did not appear for backlogs", "Academic"),
    ("The teacher uses only one language in class and students do not understand", "Academic"),
    ("I applied for re-evaluation of my exam paper but got no response", "Academic"),
    ("The hall ticket has a spelling mistake in my name", "Academic"),
    ("My semester registration was not processed despite paying the fees", "Academic"),
    ("The professor gave marks only to students who were personally known to them", "Academic"),
    ("The exam center allotted to me is 50 km away without any justification", "Academic"),
    ("My elective subject choice was overridden and I was put in a subject I did not choose", "Academic"),
    ("Faculty is teaching beyond the approved syllabus and testing students on it", "Academic"),
    ("I did not receive my marksheet even though results were announced two months ago", "Academic"),
    ("The practical exam was conducted without prior notice to students", "Academic"),
    ("The professor frequently cancels lectures without any makeup class", "Academic"),
    ("My project viva was rescheduled three times causing significant stress", "Academic"),
    ("I have a backlog in a subject I never failed according to my answer sheet", "Academic"),
    ("The exam hall was overcrowded and seating arrangement was not proper", "Academic"),
    ("A faculty member is biased against certain students when giving grades", "Academic"),
    ("I was not allowed to write the exam due to a documentation error", "Academic"),
    ("The assignment submission deadline was shortened without notice", "Academic"),
    ("My name is missing from the final year examination form", "Academic"),
    ("The professor does not explain topics clearly and students are struggling", "Academic"),
    ("There is a discrepancy between my internal marks and what is shown on portal", "Academic"),
    ("The college did not inform me about the supplementary exam schedule", "Academic"),
    ("I need a duplicate marksheet but the academic office is not responding", "Academic"),
    ("The attendance requirement policy was changed in the middle of the semester", "Academic"),
    ("My research project supervisor has been unresponsive for over a month", "Academic"),
    ("I was penalized for late submission of a document the college delayed giving me", "Academic"),
    ("The practical sessions are conducted without proper equipment in the lab", "Academic"),
    ("My improvement exam result has not been updated on the portal", "Academic"),
    ("The faculty member reads directly from slides without any explanation", "Academic"),
    ("I have a grade mismatch in my final year subject results", "Academic"),
    ("The syllabus document provided at the start of semester is incomplete", "Academic"),
    ("I was not provided a hall ticket despite completing all formalities", "Academic"),
    ("My transcript has a wrong date of birth printed on it", "Academic"),
    ("The professor is teaching a subject they are not qualified to teach", "Academic"),
    ("I was given zero marks in an assignment I submitted on time", "Academic"),
    ("The subject timetable keeps changing every week disrupting preparation", "Academic"),
    ("I need a migration certificate but the academic section has been delaying it", "Academic"),
    ("My result was withheld despite having no dues and completing all exams", "Academic"),
    ("The lecture notes shared by the professor are incomplete and unclear", "Academic"),
    ("A guest lecture was made compulsory and my attendance suffered because of it", "Academic"),
    ("I have applied for an internship NOC but the academic section has not issued it", "Academic"),
    ("My subject registration shows wrong subject codes for this semester", "Academic"),
    ("The midterm exam paper had questions outside the announced syllabus", "Academic"),
    ("I was asked to pay extra for a practical component that should be included in fees", "Academic"),
    ("The professor shares answer keys before all students have submitted the paper", "Academic"),
    ("I failed in a subject due to a mistake in evaluating my answer sheet", "Academic"),
    ("The college has not provided an academic calendar for this semester", "Academic"),
    ("I need a character certificate urgently but have not received it in three weeks", "Academic"),
    ("My CGPA calculation appears wrong compared to my individual subject grades", "Academic"),
    ("The thesis submission guidelines were changed after I had already formatted mine", "Academic"),
    ("Lab attendance and written exam attendance are being merged incorrectly", "Academic"),
    ("I was marked for academic dishonesty without any evidence or fair hearing", "Academic"),
    ("The examination fee was collected but I was not included in the exam register", "Academic"),
    ("My project guide was changed without my knowledge or consent", "Academic"),
    ("The faculty is not providing feedback on submitted assignments", "Academic"),
    ("I have a grievance about the question paper being leaked before the exam", "Academic"),
    ("My study leave application was rejected without any explanation", "Academic"),
    ("The college denied me a gap certificate which I need for university admission", "Academic"),
    ("I applied for branch transfer on academic grounds but received no reply", "Academic"),
    ("The professor deducted marks for absence during a college-sanctioned event", "Academic"),
    ("The lab report format was changed after submission leading to mass failure", "Academic"),
    ("I have not received my verified documents from the academic office for three months", "Academic"),
    ("The professor made incorrect personal comments about my academic performance", "Academic"),
    ("My elective subject has only three students and the class was cancelled", "Academic"),
    ("The grading scheme used for our batch is different from previous batches", "Academic"),
    ("I need a provisional certificate for a job application but cannot get it issued", "Academic"),
    ("The exam question paper had printing errors that caused confusion", "Academic"),
    ("I was not informed about a mandatory project presentation that affected my grade", "Academic"),
    ("The internal assessment criteria were not clearly communicated at the semester start", "Academic"),
    ("Faculty attendance in our department is very irregular affecting our learning", "Academic"),
    ("The academic office has incorrect records about my year of admission", "Academic"),

    # ── LIBRARY (80 samples) ─────────────────────────────────
    ("The book I need for my exam is always issued to someone else and never available", "Library"),
    ("The library membership card I applied for has not been issued after three weeks", "Library"),
    ("I was charged a late fine for a book I returned on time but it was not scanned", "Library"),
    ("The reading room in the library is always too noisy for studying", "Library"),
    ("The library catalog website is not loading for the past several days", "Library"),
    ("Several reference books in the library are very old and outdated editions", "Library"),
    ("The library does not have enough copies of the textbooks for our course", "Library"),
    ("I found torn and damaged pages in a library book that was issued to me", "Library"),
    ("The air conditioning in the reading room is not working during summer", "Library"),
    ("The librarian refused to issue a book without a valid reason", "Library"),
    ("The library closes early on Saturdays affecting students who study on weekends", "Library"),
    ("The photocopy machine in the library has been broken for two weeks", "Library"),
    ("I returned a book but it is still showing as issued in my library account", "Library"),
    ("The library does not have access to important journals needed for research", "Library"),
    ("There are insufficient seating arrangements in the reading room for all students", "Library"),
    ("I applied for an interlibrary loan but never heard back from the library", "Library"),
    ("The library staff is unhelpful when students ask for assistance with the catalog", "Library"),
    ("The digital library portal requires a login that has never been provided to me", "Library"),
    ("The library does not have any books in regional language for students who need them", "Library"),
    ("My library account shows a fine that was already paid months ago", "Library"),
    ("The books issued to me were infested with silverfish insects", "Library"),
    ("The library Wi-Fi does not work which makes accessing e-resources difficult", "Library"),
    ("The new books acquired by the library are not added to the catalog promptly", "Library"),
    ("The reading room lights are too dim and cause eye strain during long study sessions", "Library"),
    ("The library does not notify students when a reserved book becomes available", "Library"),
    ("I was told the book is available in catalog but could not find it on the shelf", "Library"),
    ("The library printer charges are too high compared to outside the campus", "Library"),
    ("The newspaper and magazine section of the library is never updated", "Library"),
    ("I was denied access to the library for being five minutes late", "Library"),
    ("The library has duplicate accounts for me showing two different fines", "Library"),
    ("The self-checkout machine in the library does not work properly", "Library"),
    ("The library is not open during examination study leave period", "Library"),
    ("I need access to a specific research database but the library does not subscribe to it", "Library"),
    ("Library staff misplaced the book I returned and now I am being fined for it", "Library"),
    ("The chairs in the reading room are broken and uncomfortable", "Library"),
    ("The library periodical section books are not arranged in any particular order", "Library"),
    ("I requested a book purchase but it has not been procured in six months", "Library"),
    ("The library extension counter near the hostel is always closed", "Library"),
    ("My library book was issued to someone else while it was already in my account", "Library"),
    ("There is no silence maintained in the library and students talk loudly", "Library"),
    ("The library stack area is not accessible to students which limits book access", "Library"),
    ("I was given wrong information about library hours on the college website", "Library"),
    ("The library borrowing limit of two books is insufficient for project work", "Library"),
    ("The e-library access credentials provided do not work on the database website", "Library"),
    ("Several important textbooks in the library have missing chapters", "Library"),
    ("The library does not have a dedicated section for competitive exam preparation", "Library"),
    ("I could not borrow a book because my library account had a system glitch", "Library"),
    ("The library study cubicles are always occupied and cannot be booked in advance", "Library"),
    ("The librarian asked me to wait two hours to issue a book from the closed stack", "Library"),
    ("I was not given a receipt when I paid my library fine in cash", "Library"),
    ("The library book renewal system online is not working", "Library"),
    ("The library projector used for orientation sessions is broken", "Library"),
    ("Books donated by alumni are not being added to the library catalog", "Library"),
    ("The reading room is used for storage of equipment and reduces study space", "Library"),
    ("The library fine amount was doubled without informing students", "Library"),
    ("I cannot find any books on my research topic in the library collection", "Library"),
    ("The library subscription to a specific journal has lapsed and access is gone", "Library"),
    ("My library card was deactivated without any prior notice or warning", "Library"),
    ("The library does not have a facility to request books from other branches", "Library"),
    ("I received a damaged book from the library and was still charged a fine", "Library"),
    ("The library app on my phone shows incorrect due dates for my issued books", "Library"),
    ("The reference section of the library has books that are not for borrowing but are missing", "Library"),
    ("The library does not open on Sundays even though exams start on Monday", "Library"),
    ("I found the same book listed twice in the catalog but cannot find either copy", "Library"),
    ("The library staff does not help students use the online journal access system", "Library"),
    ("There is no facility for group study or discussion rooms in the library", "Library"),
    ("The library has not updated its collection with books from the new syllabus", "Library"),
    ("I need a no dues certificate from the library but it is taking too long to issue", "Library"),
    ("The library does not allow students to take notes from reference books", "Library"),
    ("I submitted a book but the librarian did not process the return immediately", "Library"),
    ("The catalog system shows wrong shelf locations for most of the books", "Library"),
    ("The library closes during lunch break which is the only free time many students have", "Library"),
    ("I have been charged fine for a book that I never borrowed", "Library"),
    ("The library stock verification is done during exam time affecting student access", "Library"),
    ("I applied for a library no objection certificate for hostel clearance but it is pending", "Library"),
    ("The library study area does not have enough power sockets for laptop charging", "Library"),
    

    # ── TRANSPORT (80 samples) ───────────────────────────────
    ("The college bus is always 30 to 40 minutes late every morning", "Transport"),
    ("The bus driver drives very rashly and students feel unsafe during the journey", "Transport"),
    ("The bus route was changed without informing the students on that route", "Transport"),
    ("The college bus does not stop at the designated stop near my area", "Transport"),
    ("My bus pass has not been issued even after submitting the application two weeks ago", "Transport"),
    ("The bus conductor misbehaved with female students during the journey", "Transport"),
    ("The college bus is always overcrowded and students have to stand the whole journey", "Transport"),
    ("The bus does not arrive to pick students up after evening classes", "Transport"),
    ("I was left behind by the college bus even though I was at the stop on time", "Transport"),
    ("The air conditioning in the college bus is broken and it is very hot inside", "Transport"),
    ("The college bus does not run on alternate Saturdays without prior notice", "Transport"),
    ("The bus timing was changed but I was not informed and I missed college", "Transport"),
    ("The college bus breaks down frequently and students are stranded on the road", "Transport"),
    ("There is no bus facility for students living beyond 10 km from college", "Transport"),
    ("The bus pass fee was increased without any official communication", "Transport"),
    ("The college van provided for field trips is in very poor condition", "Transport"),
    ("The driver of bus route 3 uses his phone while driving", "Transport"),
    ("The bus does not have working seat belts which is a safety concern", "Transport"),
    ("The bus departure time from college in the evening was preponed without notice", "Transport"),
    ("The college bus does not have a first aid kit despite college rules", "Transport"),
    ("I submitted my bus pass renewal form but my pass expired with no renewal", "Transport"),
    ("The bus does not wait for students even for two minutes after the scheduled time", "Transport"),
    ("The college transport office is unresponsive to complaints about buses", "Transport"),
    ("The bus route 5 was discontinued and no alternative was provided", "Transport"),
    ("I was overcharged for the bus pass and not given a refund", "Transport"),
    ("The bus has a water leakage from the roof during monsoon season", "Transport"),
    ("There is no shelter at the college bus stop for students waiting in rain", "Transport"),
    ("The college bus is not sanitized regularly which is a hygiene concern", "Transport"),
    ("The bus driver does not stop at all the listed stops on the route", "Transport"),
    ("The bus capacity is 40 but over 70 students are being loaded daily", "Transport"),
    ("The college did not arrange any transport for an announced holiday event", "Transport"),
    ("My transport fee was deducted from my account but bus pass was not given", "Transport"),
    ("The college bus timetable on the website is outdated and incorrect", "Transport"),
    ("Students who pay transport fees are told there is no seat available in the bus", "Transport"),
    ("The bus ride takes two hours due to a very long and inefficient route", "Transport"),
    ("The college bus driver does not have a valid heavy vehicle license", "Transport"),
    ("The emergency exit of the college bus is blocked by luggage", "Transport"),
    ("There is no GPS tracking for college buses so parents cannot monitor safety", "Transport"),
    ("The bus arrives at college too early before classrooms are even open", "Transport"),
    ("I need a refund for my bus pass as I moved closer to the college", "Transport"),
    ("The college bus driver is often drunk and students have complained before", "Transport"),
    ("No bus is arranged for students who have exams on Sunday", "Transport"),
    ("The transport department did not arrange buses for the industrial visit", "Transport"),
    ("The college bus does not have adequate lighting inside for evening return trips", "Transport"),
    ("There are only three buses for over 600 students living in the same direction", "Transport"),
    ("The bus horn is extremely loud and causes a disturbance in residential areas", "Transport"),
    ("The bus pass is not accepted by conductors on certain days without reason", "Transport"),
    ("The college does not provide any transport for students on exam duty", "Transport"),
    ("The bus route passes through a dangerous stretch of road without divider", "Transport"),
    ("Students were dropped far from their homes on the last day without notice", "Transport"),
    ("I applied for a transport concession but was told I am not eligible without reason", "Transport"),
    ("The bus engine makes a very loud noise and appears to need urgent servicing", "Transport"),
    ("College arranged only one bus for an event that 200 students were attending", "Transport"),
    ("The bus pass photo is outdated and conductors refuse to accept it", "Transport"),
    ("There is no provision for students with disabilities in the college bus", "Transport"),
    ("The college did not run any buses during the sudden hartal causing students to miss exams", "Transport"),
    ("The bus route schedule is not displayed anywhere at the college bus stop", "Transport"),
    ("My bus pass was stolen and the college is charging full fees to reissue it", "Transport"),
    ("The transport department never picks up phone calls or replies to emails", "Transport"),
    ("The bus conductor gives change from the fare and pockets some money regularly", "Transport"),
    ("I was denied boarding the college bus despite having a valid pass", "Transport"),
    ("The college bus takes an additional one hour due to diversion on the route", "Transport"),
    ("The bus tyres appear bald and worn out which is a road safety issue", "Transport"),
    ("Students are asked to stand outside the bus in rain while waiting for late driver", "Transport"),
    ("The driver plays very loud film music which is disturbing for students", "Transport"),
    ("The bus pass renewal process requires physical submission which is inconvenient", "Transport"),
    ("No bus was provided to students travelling for a college-mandated sports event", "Transport"),
    ("The bus frequently has a foul smell inside due to lack of cleaning", "Transport"),
    ("I was charged double the fare because the conductor said my pass had expired", "Transport"),
    ("The college bus route does not cover the new residential areas near campus", "Transport"),
    ("The bus driver took a personal detour adding 40 minutes to the trip", "Transport"),
    ("The college has not added any new buses despite student enrollment increasing", "Transport"),
    ("I need a transport no dues certificate for my convocation but cannot get it", "Transport"),
    ("The college bus stop inside campus is too far from the academic block", "Transport"),
    ("The college transport office has wrong address recorded for my bus route", "Transport"),
    ("The bus was cancelled on a day we had an important internal examination", "Transport"),

    # ── FINANCE (80 samples) ─────────────────────────────────
    ("My scholarship amount has not been credited despite submitting all documents", "Finance"),
    ("I paid the exam fee online but my name does not appear in the exam register", "Finance"),
    ("The college is charging a fee for a facility that I do not use", "Finance"),
    ("I was charged a late fee even though I paid on time and have the receipt", "Finance"),
    ("My tuition fee refund application has been pending for three months", "Finance"),
    ("The fee receipt given to me has an incorrect amount printed on it", "Finance"),
    ("I was charged twice for the same fee and one payment needs to be refunded", "Finance"),
    ("The college fee structure is not clearly published for new students", "Finance"),
    ("The scholarship form is available only in one language which I do not read", "Finance"),
    ("My government scholarship was rejected due to wrong data entered by college", "Finance"),
    ("The demand note received from the college has an extra charge with no explanation", "Finance"),
    ("I cannot pay fees online because the payment gateway keeps showing an error", "Finance"),
    ("The college has deducted money from the caution deposit without informing me", "Finance"),
    ("My fee payment confirmation email did not arrive and the portal shows pending", "Finance"),
    ("The college charged me for a hostel room even after I vacated it", "Finance"),
    ("I applied for a fee installment plan but it was rejected without reason", "Finance"),
    ("The college has not refunded the security deposit even after I left the hostel", "Finance"),
    ("I was fined for not wearing ID card but I had lost it and reported it earlier", "Finance"),
    ("My name is missing from the scholarship disbursal list despite full eligibility", "Finance"),
    ("The college finance office is giving different fee amounts to different students", "Finance"),
    ("I paid my fees through NEFT but it is showing as failed on the portal", "Finance"),
    ("The fee payment portal does not generate a receipt after successful payment", "Finance"),
    ("I was charged laboratory fee for a lab I never had access to", "Finance"),
    ("The caution deposit collected at admission has not been refunded after graduation", "Finance"),
    ("The college deducted library fine from my account without issuing any notice", "Finance"),
    ("I need a fee payment certificate for bank loan but the finance office is delaying it", "Finance"),
    ("The annual fee increase was not communicated before fee payment deadline", "Finance"),
    ("My merit scholarship was stopped without giving me any reason in writing", "Finance"),
    ("The finance department keeps asking for documents that have already been submitted", "Finance"),
    ("I was charged a sports fee despite being exempted due to medical reasons", "Finance"),
    ("My exam fee payment receipt was not accepted by the exam section", "Finance"),
    ("The college collected a development fee but there is no visible development", "Finance"),
    ("My scholarship disbursement has been delayed by more than six months", "Finance"),
    ("I paid fees at the counter but the teller did not give me the official receipt", "Finance"),
    ("I need a no dues certificate from finance for convocation but it is taking too long", "Finance"),
    ("The fee structure for my batch was changed midway through the course", "Finance"),
    ("I submitted the scholarship renewal form but the portal still shows it as not received", "Finance"),
    ("The finance department gave me wrong bank account details for NEFT payment", "Finance"),
    ("The college website shows a different fee than what is printed in the brochure", "Finance"),
    ("My sibling concession application for fees has been pending since last semester", "Finance"),
    ("The college charged full fees for a semester I attended only two months due to illness", "Finance"),
    ("I need a fee payment history for income tax filing but the finance office denied it", "Finance"),
    ("An extra miscellaneous fee appeared on my account without any explanation", "Finance"),
    ("My educational loan letter from the college has incorrect financial information", "Finance"),
    ("The college deducted exam re-registration fees without my consent", "Finance"),
    ("I was told I have dues but I have receipts showing all payments are complete", "Finance"),
    ("The finance office rejected my fee payment because of a minor name spelling difference", "Finance"),
    ("I need a scholarship certificate but the finance office says they do not issue it", "Finance"),
    ("The college added a sports development fee in the middle of the year without notice", "Finance"),
    ("I applied for fee waiver due to financial hardship but got no response", "Finance"),
    ("My tution fee receipt shows wrong course name which is causing issues for loan", "Finance"),
    ("The college has not submitted my scholarship details to the government portal", "Finance"),
    ("My bank charged me for a failed transaction but college also shows payment pending", "Finance"),
    ("I need a duplicate fee receipt but the finance office is asking for extra charges", "Finance"),
    ("The annual report of college fees is not publicly available for transparency", "Finance"),
    ("I was asked to pay exam fee again for a paper I already paid for", "Finance"),
    ("My scholarship renewal was denied because college submitted wrong marks to the board", "Finance"),
    ("The finance department closed counters before official closing time on fee payment day", "Finance"),
    ("I was charged a fine for late fee payment but I had an approved extension", "Finance"),
    ("College deducted mess fee for months I was on internship and not using the mess", "Finance"),
    ("The fee portal shows an outstanding balance that does not match any fee category", "Finance"),
    ("My education loan disbursement is held because college letter has wrong details", "Finance"),
    ("I paid fees in cash at the counter and lost the receipt but college has no backup record", "Finance"),
    ("The college charged enrollment fee twice for the same academic year", "Finance"),
    ("I need a certified true copy of fee payment for court proceedings but cannot get it", "Finance"),
    ("The online fee payment is only available for specific banks which I do not use", "Finance"),
    ("My scholarship bank account details were updated but the disbursement went to old account", "Finance"),
    ("The college has incorrectly marked me as a fee defaulter in the records", "Finance"),
    ("I applied for a fee concession under the sports quota but it was not applied", "Finance"),
    ("The finance office does not respond to emails within a reasonable time", "Finance"),
    ("My convocation registration was rejected due to pending dues that I have already cleared", "Finance"),
    ("The college is withholding my original documents due to a fee dispute I disagree with", "Finance"),
    ("I was charged a penalty fee for submitting documents one day late during a holiday period", "Finance"),
    ("The college claims I have transport dues even though I never used the transport service", "Finance"),
    ("I need a financial assistance application form but the finance office says it does not exist", "Finance"),
    ("The college has not processed my fee transfer after my course change request was approved", "Finance"),

    # ── DISAMBIGUATION SAMPLES (edge cases the model got wrong) ──
    # WiFi in hostel → IT (network issue, not hostel living issue)
    ("The wifi in the hostel building is not working", "IT"),
    ("Internet connection in hostel is very slow and unusable", "IT"),
    ("College network does not reach my hostel room", "IT"),
    ("WiFi password for hostel was changed and nobody informed students", "IT"),
    ("Cannot connect laptop to college wifi from hostel block", "IT"),
    ("No internet access in hostel block B entire week", "IT"),
    ("The network router in hostel corridor is broken", "IT"),
    ("Broadband connection in hostel is down since three days", "IT"),
    ("The campus WiFi does not work in the hostel area at all", "IT"),
    ("Hostel internet is so slow that I cannot attend online classes", "IT"),

    # Hostel complaints that mention connectivity — still Hostel
    ("Hostel room has no electricity since two days and warden is not responding", "Hostel"),
    ("Mess food is cold every morning and the warden does not care about complaints", "Hostel"),
    ("Hostel gate was locked at 9 PM even though curfew is supposed to be 10 PM", "Hostel"),
    ("There is no power in the hostel rooms and the warden is unavailable", "Hostel"),

    # Library fine vs Finance fee
    ("Library charged a late return fine that I already paid in cash", "Library"),
    ("My library account shows overdue fine despite returning the book on time", "Library"),
    ("Library fine was deducted from my student account without proper notice", "Library"),
    ("I need my library fine waived because the book was returned before due date", "Library"),

    # Transport vs Finance on bus pass payment
    ("Bus pass renewal fees were deducted but my pass was not renewed", "Transport"),
    ("I paid for college bus pass but conductor still refuses me entry on the bus", "Transport"),
    ("Bus pass was not given despite paying transport fees two weeks ago", "Transport"),
    ("My transport fee was paid but no bus seat has been allotted to me", "Transport"),

    # Academic vs Hostel on exams and study
    ("I cannot study in hostel because there is too much noise from other students", "Hostel"),
    ("The hostel study room is locked during exam season when we need it most", "Hostel"),
    ("My exam result has an error and the faculty is not correcting it", "Academic"),
    ("The professor is biased and gave me low marks without justification", "Academic"),
]

if __name__ == "__main__":
    from collections import Counter
    labels = [label for _, label in TRAINING_DATA]
    counts = Counter(labels)
    print(f"Total samples: {len(TRAINING_DATA)}")
    for dept, count in sorted(counts.items()):
        print(f"  {dept}: {count}")